# Generated by Django 4.0.4 on 2022-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_account_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='account_address',
            field=models.BigIntegerField(default='59145910', unique=True, verbose_name='account address'),
        ),
    ]
