# Generated by Django 4.0.4 on 2022-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='account_address',
            field=models.BigIntegerField(default='58284344', unique=True, verbose_name='account address'),
        ),
    ]
